apiVersion: v1
kind: Service
metadata:
  name: nestjs
spec:
  type: {{ .Values.nestjs.service.type }}
  ports:
  - port: {{ .Values.nestjs.service.port }}
    targetPort: 3000
  selector:
    app: nestjs